### ISSUE TITLE
minikubeでのgrafanaの起動方法

### ISSUE THREAD

**Issue by 08k0126** [takara9/vagrant-minikube#2]
「5Stepで習得 Dockerから入るKubernetes コンテナ開発からK8s本番運用まで」のP.480 に記載されているメトリックス監視基盤の利用について質問です。

上記の書籍では、heapsterとmetrics-serverを導入してメトリックス監視基盤を利用することになっております。ですが、heapsterについては、現在は導入ができないことと、書籍のp.478では、今後はmetrics-serverに移行が始まっていると書かれております。そのため、P.480 に記載されている通りにはメトリックス監視基盤は利用できないようです。

metrics-serverをp.478のやり方で導入するだけでは、以下のURLを実行しても、
`http://Vagrant-Minikubeの仮想マシンのIP:30002/`

ブラウザ上に、
```
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
```
と表示だけされて、Grafanaにアクセスができない状況となっております。

Grafanaにアクセスできるやり方などをご教示いただきたいです。

**Comment by takara9** [comment]
過去のバージョンのminikubeでは、heapster アドオンを入れるだけで、InfluxDBとGrafanaが入っていましたが、heapsterの後続となる metrics-server のアドオンを有効化しても、Prometheus と Grafanaをインストールされることはありません。 minikubeの過去のバージョンでは、K8sの範囲を超えてサービスが良かった感じがしますね。 

Qiita @yurakさんの記事 「Prometheus と Grafana を Minikube にイチから構築するステップまとめ」https://qiita.com/yurak/items/c3d098c4596aaf6ac674 が参考になると思います。

それから、Helmを利用した導入方法では、Qiita 「Kubernetesの監視#1 Promethus & Grafana on ROOK Ceph」https://qiita.com/yurak/items/c3d098c4596aaf6ac674　が参考になると思います。

**Comment by takara9** [comment]
こちらは Closeさせて頂こうと思いますが、いかがでしょうか？

**Comment by 08k0126** [comment]
今いろいろお試し中で、１点質問です。

[Qiita 「Kubernetesの監視#1 Promethus & Grafana on ROOK Ceph」](https://qiita.com/MahoTakara/items/5c980f00250a89757020)では、
`ROOK Ceph のブロックストレージを検証したメモの記事で、ダイナミック・プロビジョニング可能な永続ストレージが利用できるようになったので、この基盤を利用して、メトリックス監視の・・・`
となっておりますが、

Vagrantで起動するコードは、「https://github.com/takara9/vagrant-minikube」ではなく、
「https://github.com/takara9/vagrant-kubernetes k8s」とするべきでしょうか？

**Comment by takara9** [comment]
メトリックスデータを蓄積する時系列データベース Promethusを利用するには、データの保全性が確保された永続ボリュームが必要になると思います。そこでminikubeでは、hostpathのストレージを利用する事ができますが、ノードのストレージを利用するため、保全性が確保されている訳ではありません。つまり、ノードやストレージが失われれば、一緒にデータを失う懸念があります。
自己研鑽で Minikube + hostpathの永続ボリュームを利用して具体的な理解を進めるのは価値がありますが、本格的なK8sでの運用を考慮した学習を進めるとしたら、Glusterfsや ROOK(Ceph)などのストレージ基盤のうえに構築するのが適当と思います。 また、メトリックス管理基盤は、自前で運用しても企業の競争力に直結しないので、Promethusを自前で運用するよりも、DataDog,SysDig,StackDriverなどのクラウドのサービスを利用するべきとの考えもあります。その方が、細かく行き届いたビューが提供され、過去データの保全性も確保してくれるからです。
Grafana - Prometheus - node-exporterなどの構築は、全体を理解した上で、取り組むのが良いと思います。

**Comment by 08k0126** [comment]
ご回答いただき、ありがとうございます。

書籍の方も、過去のバージョンのminikubeを前提として書かれており、
当時とバージョンが変わっているため上記の懸念などがあることを理解しました。

＞Grafana - Prometheus - node-exporterなどの構築は、全体を理解した上で、取り組むのが良いと思います。

かつ、
まだ理解それほど進んでいない状況で取組むのは難しいとのことですので、一旦は飛ばして進めます。
学習のアドバイスまでいただき、ありがとうございます。

本件は、クローズさせていただきます。
